devices:
  - name: "leidian_1"
    connect_info: emulator-5554
    port: 5554
    resolution: [1920, 1080]
    click_points:
      search_box: [100, 200]
      cart_button: [300, 400]
      checkout_button: [500, 600]
